### ISSUE TITLE
candidate profiles

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1401] opened 2016-08-08 12:17 UTC
Why is Hillary for America NOT listed first:
![image](https://cloud.githubusercontent.com/assets/11817734/17479437/8fbd6c02-5d40-11e6-850b-d4cfb2486262.png)

Shouldn’t the ACTIVE committee be listed first?

**Comment by noahmanger** [comment] 2016-08-09 01:35
Duplicate of https://github.com/18F/openFEC-web-app/issues/1452

**Closed by noahmanger** 2016-08-09 01:35 UTC

**Comment by jwchumley** [comment] 2016-08-17 12:16
Principal campaign committee for the selected time period should be first or only. Other committees that are related have a place lower on the screen.
Priority: High
