### ISSUE TITLE
Bug: Weekly calendar toggle 

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/openFEC-web-app#1032] opened 2016-01-14 20:49 UTC
When you toggle into the weekly view, the "quarter" and "month" buttons stop working.

![weeklyview](https://cloud.githubusercontent.com/assets/10552702/12337121/240d10e6-bad6-11e5-8e1b-ed6abbe49a41.gif)

**Comment by jmcarp** [comment] 2016-01-14 23:47
Duplicate of https://github.com/18F/fec-style/issues/224.

**Closed by jmcarp** 2016-01-14 23:47 UTC
Labels: bug
