### ISSUE TITLE
Design search interface for audit info

### ISSUE THREAD

**Issue by jwchumley** [18F/openFEC-web-app#2261] opened 2017-08-15 12:57 UTC
Design and build audit search front end template for audit info

* This should have been on 3.3 but wasn't in Muraly
 @rjayasekera @hcaofec

**Comment by jenniferthibault** [comment] 2017-09-06 22:49
**Status update:**

Had a great and helpful meeting with folks from Audit today who helped me understand the internal use cases for the audit reports and the search interface. 🔏  [Audit report search stakeholder notes](https://docs.google.com/a/gsa.gov/document/d/19dt8jZyurTJlW2lrpr7pv7ItWUIj6oRQFyTxp2njC-s/edit?usp=sharing)

Since I'm OOO for the next few days overlapping sprint planning, I wanted to attach an early mockup, but it's definitely not finished. The arrangement and design decisions of the core columns of the table are more mature than the filter panel, which is very work in progress. The folks from audit today had some great ideas about existing filter problems we could solve through different interface elements

![screen shot 2017-09-06 at 6 42 43 pm](https://user-images.githubusercontent.com/11636908/30137892-861b00ae-9333-11e7-959e-d9493419d737.png)

This concept is not yet ready for feedback, and is just to show progress at the moment and clear up any blockers to starting basic implementation.

I also have a lead coming in from Christian in the Press office who will help us understand how members of the public use audit reports, by sharing with me the most common questions and answers the press office gets about them.

If folks are ready to move on implementation, I don't think the filter panel should hold anything up, it seems like there's enough to start on here. Sorry to leave this one hanging more than the rest!

**Comment by jenniferthibault** [comment] 2017-09-06 22:49
^ Edit: This concept is not yet ready for feedback, and is just to show progress at the moment and clear up any blockers to starting basic implementation

**Comment by jenniferthibault** [comment] 2017-09-18 16:18
Here's a more polished version, followed by some documentation around the thinking behind it:

![screen shot 2017-09-29 at 1 32 27 pm](https://user-images.githubusercontent.com/11636908/31028029-7116d1f8-a51a-11e7-983a-c0ccfa2b7ad4.png)



## Design notes about changes:
This design adapts the existing audit report search into patterns and principles used by the new site. It introduces the filter panel and tag system used across the rest of the site. The focus of this version is to get the existing data on the new site, and achieving quick wins that improve known challenges or points of confusion with the previous interface and subject matter.

**Display of table and columns**
- We dropped the "Committee type" column from the new layout. This is primarily because of the limited space in the layout, but also because that adds the least value as a sortable column, especially when it's available as a filter.
  - ![screen shot 2017-09-18 at 11 55 52 am](https://user-images.githubusercontent.com/11636908/30551344-2df2dd14-9c68-11e7-92f2-341427fe4df2.png)
- We also moved the "Election cycle" and "Final report" columns next to each other so that it's easier to quickly view the span in time
- The first column now displays the name of the audit report, not just the name of the committee audited. While the report title usually/always contains the committee name, we need to indicate to users that clicking it will open the audit report, _not_ lead them to the committee's profile page. Throughout the rest of the site, anytime the name of a committee is linked, it directs you to the profile page, so it's important here to indicate that this will open an report instead.
  - ![screen shot 2017-09-18 at 11 59 02 am](https://user-images.githubusercontent.com/11636908/30551508-a190a116-9c68-11e7-9569-b311dd601be3.png)
- To be consistent with our table pattern through the rest of the site, when there's no information present in a field, we tell people why instead of leaving it blank. In this case, it applies tp the "Candidate" column.
  - ![screen shot 2017-09-18 at 12 05 35 pm](https://user-images.githubusercontent.com/11636908/30551746-8a7d8baa-9c69-11e7-97f9-863ce15538a6.png)
- An enhancement is that we should be able to connect the references to authorized candidates to their profile pages directly from the tables

**Display of filters**

- Re-organized the filter list to put the candidate/committee fields first— this makes it easier to find a specific audit report first, if you're looking to see if a specific entity has been audited (which is one of the top questions from members of the public)

  - ![screen shot 2017-09-29 at 1 33 43 pm](https://user-images.githubusercontent.com/11636908/31028082-a086c934-a51a-11e7-8bfa-a71daebd5eb1.png)


- Show the relationship between the Tier 1 & Tier 2 issues and categories: clarify that one is not more severe than the other. This can be resolved most simply with some small changes to the field labels ("Subcategories") and by nesting that shows that the second tier is a child category.
  - ![screen shot 2017-09-18 at 12 11 43 pm](https://user-images.githubusercontent.com/11636908/30551974-67fe103a-9c6a-11e7-8dd0-ae079e3b37df.png)

### Applying filters and tags (interactions)
When we move to the new site's templates, there will be one big difference in the filter behaviors: previously, you could only apply one filter in each. The new site allows you to apply multiple filters from categories where it makes sense. For example, we should allow searching by multiple committees, candidates, or types of each. 

 **Filter space**

![screen shot 2017-09-29 at 1 35 12 pm](https://user-images.githubusercontent.com/11636908/31028131-d3b29bf8-a51a-11e7-901f-176001d052ae.png)




**Tag space**

![screen shot 2017-09-19 at 12 17 32 pm](https://user-images.githubusercontent.com/11636908/30603048-62365994-9d34-11e7-9f79-6b0cad2bb90b.png)


## Next steps:
- File enhancement issues that came out of research with the folks in Audit (@jenniferthibault)
- Document issue for experience of what happens after you click into an audit report link (@jenniferthibault)
- @rjayasekera @pkfec & @jenniferthibault sync on how to move this to implementation

**Comment by jenniferthibault** [comment] 2017-09-19 17:28
Based on pairing today, it was determined that the suggestion to allow multiple finding filters at once would create confusing result lists because of the way the data is structured in the API. Base don this, we're going to keep the original functionality of only allowing one category/subcategory at a time.

Additionally, the designs were edited to show that we need to support searching for audit reports across a range of time, instead of only by one year/election cycle at a time. This change needs to also happen in the API.

___
Based on this, and talking through filter and tag functionality, the aim is to implement the functionality as designed (accepting multiple entries for candidate, committee, and type of) but if that blocks things significantly, the priority is to focus on replace existing functionality, so limiting to one value is an acceptable first step.

**Comment by jenniferthibault** [comment] 2017-09-29 17:34
Closing in favor of more specific implementation issues and will carry the designs over into those issues.

**Closed by jenniferthibault** 2017-09-29 17:34 UTC
Labels: Waltham shutdown, Work: Design, Work: Front-end
