### ISSUE TITLE
Fundraising comparison (in 2016 presidential election) showing unexpected candidates as default

### ISSUE THREAD

**Issue by jenniferthibault** [18F/openFEC-web-app#1355] opened 2016-07-13 23:57 UTC
https://beta.fec.gov/data/elections/president/2016/

These candidates are supposed to be listed/shown by amount raised so that the most interesting candidates will show up by default. I was looking at something else, and noticed that I didn't recognize any of these candidates, and the ones I expected to be there are halfway down the list.

Is the data wrong here? Or did something in the default setting break?

![screen shot 2016-07-13 at 7 53 25 pm](https://cloud.githubusercontent.com/assets/11636908/16823662/b3bde3be-4933-11e6-814f-f05c237b0f70.png)

cc @noahmanger @LindsayYoung

**Comment by jenniferthibault** [comment] 2016-07-13 23:58
This may apply to other elections/type of elections, but this is the only one I recognize

**Comment by noahmanger** [comment] 2016-07-14 00:08
Arg! Good catch. This looks related to the presidential candidate sort bug we were dealing with the last release. We fixed it for the top lists and presidential candidate table page, but not here. @jontours , I believe you figured this out, right?

**Comment by ccostino** [comment] 2016-07-18 14:38
I'm not seeing any broken query string parameters here so I am guessing something is just missing from the query.  @jenniferthibault and @noahmanger, what were you expected to see here and/or how should the comparison table be sorted?  The same way as the tables above it?

**Comment by LindsayYoung** [comment] 2016-07-18 14:45
I think the cause of this is https://github.com/18F/openFEC/issues/1819

**Comment by ccostino** [comment] 2016-07-18 14:47
Ah, so this isn't necessarily a web-app bug then, it's an issue with the API endpoint itself?

**Comment by jenniferthibault** [comment] 2016-07-18 14:57
@ccostino I can't speak to if the problem comes from the API or web app, but the expected behavior is that the 10 candidates pre-selected on page load to be the 10 with the largest amounts raised out of the whole set of candidates.

**Comment by ccostino** [comment] 2016-07-18 14:58
Okay, thanks @jenniferthibault!

**Comment by ccostino** [comment] 2016-07-18 15:27
Yes, the issue is on the API side, the results that come back are not sorted properly and none of the records contain a `total_receipts` count above 0.

**Comment by ccostino** [comment] 2016-07-18 20:33
Turns out there was an issue on the web app side as well with a missing flag from the query, PR coming in for that!

**Comment by ccostino** [comment] 2016-07-19 13:08
Both the API and web app PRs are merged to fix this, so I am going to close this issue.

**Closed by ccostino** 2016-07-19 13:08 UTC
Labels: Bug, Work: Back-end
