### ISSUE TITLE
all candidates - filter

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1413] opened 2016-08-08 12:27 UTC
In the district field, it goes up to 99

![image](https://cloud.githubusercontent.com/assets/11817734/17479681/db971906-5d41-11e6-84c2-3787e7b8d61e.png)

Can the district field be tied to the state that is selected, for example, a user selects Virginia, in the district field 1 thru 11 appears.

**Comment by noahmanger** [comment] 2016-08-09 01:25
Duplicate of https://github.com/18F/openFEC-web-app/issues/1480

**Closed by noahmanger** 2016-08-09 01:25 UTC
