### ISSUE TITLE
Page display on dev

### ISSUE THREAD

**Issue by LindsayYoung** [18F/openFEC-web-app#1350] opened 2016-07-11 15:26 UTC
On the dev web app, I think a zero is missing somewhere.Looks like we only show a tenth of the per page count https://fec-dev-proxy.18f.gov/data/receipts/?two_year_transaction_period=2016&min_date=01-01-2015&max_date=07-11-2016

**Comment by noahmanger** [comment] 2016-07-11 16:21
Strange!  I'll look into it.

**Comment by jontours** [comment] 2016-07-11 16:47
Hmm.  I think the bug might be on the API.  Could be a bug I introduced with the candidate totals fix for the last release, all 30 records are visible if the negative sign for reverse sort is removed from the sort parameter.

**Comment by jontours** [comment] 2016-07-12 14:53
@LindsayYoung @noahmanger this seems to have resolved itself...somehow.

**Comment by jontours** [comment] 2016-07-12 14:55
Actually there is still a problem, it's just showing slightly more records now, just not 30 as it should.

**Comment by noahmanger** [comment] 2016-07-13 00:20
Yep, I can verify it's a bug with the sort column. Sorting on other columns (like date) is fine. Assigning to @jontours .

**Comment by jontours** [comment] 2016-07-13 20:30
@noahmanger @LindsayYoung @ccostino After chasing my tell for a bit, and learning a good bit of SqlAlchemy, it seems the problem with this lies within the table `ofec_sched_a_master`.  I thought this table would use `sub_id` as its primary key, as it is essentially just a copy of `fec_vsum_sched_a`, which does enforce the primary key constraint on that column

However it seems in `ofec_sched_a_master` we are creating duplicate records somehow.  An example of this, if you log into dev database, and run this query:

`select * from ofec_sched_a_master where sub_id = 4071120161306493552`

This returns two records, however there is only one record for this `sub_id` in `fec_vsum_sched_a`.  I'm not sure how that happened, could it had happened in partitioning somehow?

But the ORM for SqlAlchemy sees this in the query and only uses one record, so although query.count() says the query returns 30 records, all the duplicates are only included once.  So that's how the query returns, say 17 records, instead of 30.

**Comment by LindsayYoung** [comment] 2016-07-13 21:57
Do you think that was caused by repartitioning? Maybe when we did the `update_all` to get the last round of schema changes it just added everything to the table again

**Comment by ccostino** [comment] 2016-07-14 04:33
Oh wow, that's strange.  Repartitioning wipes out the previous set of tables and populates the new ones with the data from the source table (`fec_vsum_sched_*` in this case), so we don't have to worry about old data sticking around, it's always fresh and one set whenever the tables are repartitioned.  Also, `ofec_sched_a_master` itself does not contain any records, only the child tables do - you can see this if you run a query prefaced with an `explain` or `explain analyze`.  You can also verify by explicitly specifying to select records from one table only:  `select count(*) from only ofec_sched_a_master;`  You'll see this as the result:

```
 count
-------
     0
(1 row)
```

We did have an issue before where records that had dates that encompassed different years were going into the wrong child tables or showing up in multiple tables.  In the case of schedule a data, this was caused by the `contb_receipt_dt` being one year, e.g., 2014, but the `rpt_yr` being a different year, e.g., 2015.  The original checks were against `rpt_yr` only, but we addressed this with the addition of calculating the `two_year_transaction_period` and basing everything off of that.

In this particular case, the record in question in the `fec_vsum_sched_a` table has the following dates:

```
  contb_receipt_dt   | rpt_yr
---------------------+--------
 2016-07-02 00:00:00 |   2016
```

So the issue definitely isn't with the date since it's 2016 in both cases (and we've verified that the `two_year_transaction_period` checks also work from before).  Somehow it still exists twice within the partitioned table though, so the next question to answer is which child table(s) does this record exist in?  Hopefully once we get that answered we can unwind how this all came to be!

**Comment by ccostino** [comment] 2016-07-14 04:53
D'oh, was thinking a bit too hard on how to figure this out as `explain analyze` tells you everything: `explain analyze select * from ofec_sched_a_master where sub_id = 4071120161306493552;`

```
Append  (cost=0.00..169.41 rows=21 width=2736) (actual time=0.148..0.150 rows=2 loops=1)
   ->  Seq Scan on ofec_sched_a_master  (cost=0.00..0.00 rows=1 width=5657) (actual time=0.000..0.000 rows=0 loops=1)
         Filter: (sub_id = 4071120161306493552::numeric)
   ->  Index Scan using ix_ofec_sched_a_1977_1978_tmp_sub_id on ofec_sched_a_1977_1978  (cost=0.42..8.44 rows=1 width=3634) (actual time=0.010..0.010 rows=0 loops=1)
         Index Cond: (sub_id = 4071120161306493552::numeric)
   ->  Index Scan using ix_ofec_sched_a_1979_1980_tmp_sub_id on ofec_sched_a_1979_1980  (cost=0.42..8.44 rows=1 width=3177) (actual time=0.007..0.007 rows=0 loops=1)
         Index Cond: (sub_id = 4071120161306493552::numeric)
   ->  Index Scan using ix_ofec_sched_a_1981_1982_tmp_sub_id on ofec_sched_a_1981_1982  (cost=0.42..8.44 rows=1 width=3627) (actual time=0.007..0.007 rows=0 loops=1)
         Index Cond: (sub_id = 4071120161306493552::numeric)
   ->  Index Scan using ix_ofec_sched_a_1983_1984_tmp_sub_id on ofec_sched_a_1983_1984  (cost=0.42..8.44 rows=1 width=3628) (actual time=0.006..0.006 rows=0 loops=1)
         Index Cond: (sub_id = 4071120161306493552::numeric)
   ->  Index Scan using ix_ofec_sched_a_1985_1986_tmp_sub_id on ofec_sched_a_1985_1986  (cost=0.42..8.44 rows=1 width=3625) (actual time=0.006..0.006 rows=0 loops=1)
         Index Cond: (sub_id = 4071120161306493552::numeric)
   ->  Index Scan using ix_ofec_sched_a_1987_1988_tmp_sub_id on ofec_sched_a_1987_1988  (cost=0.42..8.44 rows=1 width=3628) (actual time=0.006..0.006 rows=0 loops=1)
         Index Cond: (sub_id = 4071120161306493552::numeric)
   ->  Index Scan using ix_ofec_sched_a_1989_1990_tmp_sub_id on ofec_sched_a_1989_1990  (cost=0.42..8.44 rows=1 width=3330) (actual time=0.006..0.006 rows=0 loops=1)
         Index Cond: (sub_id = 4071120161306493552::numeric)
   ->  Index Scan using ix_ofec_sched_a_1991_1992_tmp_sub_id on ofec_sched_a_1991_1992  (cost=0.42..8.44 rows=1 width=3621) (actual time=0.006..0.006 rows=0 loops=1)
         Index Cond: (sub_id = 4071120161306493552::numeric)
   ->  Index Scan using ix_ofec_sched_a_1993_1994_tmp_sub_id on ofec_sched_a_1993_1994  (cost=0.42..8.44 rows=1 width=3617) (actual time=0.006..0.006 rows=0 loops=1)
         Index Cond: (sub_id = 4071120161306493552::numeric)
   ->  Index Scan using ix_ofec_sched_a_1995_1996_tmp_sub_id on ofec_sched_a_1995_1996  (cost=0.43..8.45 rows=1 width=3508) (actual time=0.006..0.006 rows=0 loops=1)
         Index Cond: (sub_id = 4071120161306493552::numeric)
   ->  Index Scan using ix_ofec_sched_a_1997_1998_tmp_sub_id on ofec_sched_a_1997_1998  (cost=0.42..8.44 rows=1 width=2863) (actual time=0.006..0.006 rows=0 loops=1)
         Index Cond: (sub_id = 4071120161306493552::numeric)
   ->  Index Scan using ix_ofec_sched_a_1999_2000_tmp_sub_id on ofec_sched_a_1999_2000  (cost=0.43..8.45 rows=1 width=2728) (actual time=0.006..0.006 rows=0 loops=1)
         Index Cond: (sub_id = 4071120161306493552::numeric)
   ->  Index Scan using ix_ofec_sched_a_2001_2002_tmp_sub_id on ofec_sched_a_2001_2002  (cost=0.43..8.45 rows=1 width=1874) (actual time=0.007..0.007 rows=0 loops=1)
         Index Cond: (sub_id = 4071120161306493552::numeric)
   ->  Index Scan using ix_ofec_sched_a_2003_2004_tmp_sub_id on ofec_sched_a_2003_2004  (cost=0.43..8.45 rows=1 width=1151) (actual time=0.007..0.007 rows=0 loops=1)
         Index Cond: (sub_id = 4071120161306493552::numeric)
   ->  Index Scan using ix_ofec_sched_a_2005_2006_tmp_sub_id on ofec_sched_a_2005_2006  (cost=0.43..8.45 rows=1 width=1364) (actual time=0.007..0.007 rows=0 loops=1)
         Index Cond: (sub_id = 4071120161306493552::numeric)
   ->  Index Scan using ix_ofec_sched_a_2007_2008_tmp_sub_id on ofec_sched_a_2007_2008  (cost=0.56..8.58 rows=1 width=1394) (actual time=0.008..0.008 rows=0 loops=1)
         Index Cond: (sub_id = 4071120161306493552::numeric)
   ->  Index Scan using ix_ofec_sched_a_2009_2010_tmp_sub_id on ofec_sched_a_2009_2010  (cost=0.43..8.45 rows=1 width=1016) (actual time=0.008..0.008 rows=0 loops=1)
         Index Cond: (sub_id = 4071120161306493552::numeric)
   ->  Index Scan using ix_ofec_sched_a_2011_2012_tmp_sub_id on ofec_sched_a_2011_2012  (cost=0.56..8.58 rows=1 width=1337) (actual time=0.008..0.008 rows=0 loops=1)
         Index Cond: (sub_id = 4071120161306493552::numeric)
   ->  Index Scan using ix_ofec_sched_a_2013_2014_tmp_sub_id on ofec_sched_a_2013_2014  (cost=0.56..8.58 rows=1 width=1336) (actual time=0.009..0.009 rows=0 loops=1)
         Index Cond: (sub_id = 4071120161306493552::numeric)
   ->  Index Scan using ix_ofec_sched_a_2015_2016_tmp_sub_id on ofec_sched_a_2015_2016  (cost=0.56..8.58 rows=1 width=1332) (actual time=0.013..0.015 rows=2 loops=1)
         Index Cond: (sub_id = 4071120161306493552::numeric)
 Planning time: 3.498 ms
 Execution time: 0.817 ms
(45 rows)
```

If you look closely at the output of the last index scan on the `ofec_sched_a_2015_2016` table, you can see both rows live there: `(cost=0.56..8.58 rows=1 width=1332) (actual time=0.013..0.015 **rows=2** loops=1)`

This is very strange though because we have a primary key constraint on the table!  The master table has it defined as a part of its schema (`\d+ ofec_sched_a_master;`): `"ofec_sched_a_master_tmp_pkey1" PRIMARY KEY, btree (sub_id)`

And the child tables should as well, or so I thought: `\d+ ofec_sched_a_2015_2016;` yields this after all of the column information:

```
Indexes:
    "ix_ofec_sched_a_2015_2016_tmp_clean_contbr_id" btree (clean_contbr_id)
    "ix_ofec_sched_a_2015_2016_tmp_cmte_id" btree (cmte_id, contb_aggregate_ytd, sub_id)
    "ix_ofec_sched_a_2015_2016_tmp_contb_aggregate_ytd" btree (contb_aggregate_ytd, sub_id)
    "ix_ofec_sched_a_2015_2016_tmp_contb_receipt_amt" btree (contb_receipt_amt, sub_id)
    "ix_ofec_sched_a_2015_2016_tmp_contb_receipt_dt" btree (contb_receipt_dt, sub_id)
    "ix_ofec_sched_a_2015_2016_tmp_contbr_city" btree (contbr_city)
    "ix_ofec_sched_a_2015_2016_tmp_contbr_st" btree (contbr_st)
    "ix_ofec_sched_a_2015_2016_tmp_contributor_employer_text" gin (contributor_employer_text)
    "ix_ofec_sched_a_2015_2016_tmp_contributor_name_text" gin (contributor_name_text)
    "ix_ofec_sched_a_2015_2016_tmp_contributor_occupation_text" gin (contributor_occupation_text)
    "ix_ofec_sched_a_2015_2016_tmp_entity_tp" btree (entity_tp)
    "ix_ofec_sched_a_2015_2016_tmp_image_num" btree (image_num)
    "ix_ofec_sched_a_2015_2016_tmp_is_individual" btree (is_individual)
    "ix_ofec_sched_a_2015_2016_tmp_rpt_yr" btree (rpt_yr)
    "ix_ofec_sched_a_2015_2016_tmp_sub_id" btree (sub_id)
    "ix_ofec_sched_a_2015_2016_tmp_two_year_transaction_period" btree (two_year_transaction_period)
Check constraints:
    "check_two_year_transaction_period" CHECK (two_year_transaction_period = ANY (ARRAY[2015, 2016]))
Inherits: ofec_sched_a_master
```

Notice that there's no primary key constraint listed.  What I'm not sure of at the moment is if it's enough to inherit from the parent table, or if it still needs to be explicitly defined on the child table(s) as well.  That's a matter of going through the [PostgreSQL Partitioning documentation](https://www.postgresql.org/docs/9.4/static/ddl-partitioning.html) and [this great blog post](https://www.depesz.com/2015/06/07/partitioning-what-why-how/) explaining it step-by-step.

This also still doesn't quite answer how the record ended up in there twice, unless we ran into a weird race condition where the repartitioning took place but during that time the queue tables were also filled.  Perhaps the repartitioning picked up the new record, but with it having already been placed in the queue as well, it was copied in again during the nightly refresh shortly afterward.  If not having a primary key defined on the child table allows us to violate the uniqueness that should be accounted for since it's defined on the parent table, that could be the reason why and we'd have to explicitly add the same primary key constraint on the child tables.

**Comment by ccostino** [comment] 2016-07-14 04:59
And if that is indeed the case (we'd need to come up with some way to test this scenario), I'm guessing we'll also need to add in some error handling to the queue processing logic upon insertion so it skips the record if it violates the unique constraint that should be present ([which starts around here](https://github.com/18F/openFEC/blob/develop/webservices/partition/base.py#L172)).

**Comment by jontours** [comment] 2016-07-14 13:28
Strange indeed! Yeah it _should_ be a simple matter to add in some logic to just keep trucking if it encounters a primary key violation.

**Comment by jontours** [comment] 2016-07-14 13:28
I'll give that documentation some time, I believe I read some of it before but now may be a more proper time to really read it.

**Comment by ccostino** [comment] 2016-07-14 14:12
Awesome, let me know if there's anything more I can do or help with or if you want to pair or anything on it. :-)

**Comment by LindsayYoung** [comment] 2016-07-14 14:40
My guess for how it happened is that we are now rebuilding the aggregates once a week, but when we do that, we also need to empty the new and old ques so they don't get applied the next night. 

Also, we might want to add logic to check that we are not double inserting anything, and turn off the updates on feature, so we can rule that out too.

**Comment by jontours** [comment] 2016-07-14 15:17
Here is the reference for the SqlAlchemy problem: http://stackoverflow.com/questions/19409278/querying-for-all-results-in-sqlalchemy-0-7-10

The quote about a "holding zone" from the SqlAlchemy docs was interesting.  Really SqlAlchemy?

**Comment by ccostino** [comment] 2016-07-14 15:44
One more doc that might of interest for partitioning: https://wiki.postgresql.org/wiki/Table_partitioning

Also, @LindsayYoung, I think you're right about clearing out the queues.  We don't do that with the rebuild step but we do with the update nightly step, seen in [the two methods here] (https://github.com/18F/openFEC/blob/develop/manage.py#L157).

We definitely need to shut the updates off in the `feature` space, that is likely causing some confusion and problems.

**Comment by LindsayYoung** [comment] 2016-07-14 15:50
Que issue https://github.com/18F/openFEC-web-app/issues/1357
feature issue https://github.com/18F/openFEC-web-app/issues/1358

**Comment by ccostino** [comment] 2016-07-14 15:57
Actually, there are a couple of things that need to change here it looks like.  The `update_aggregates` management command starts off with a call to the `update_aggregates` function that we have defined in the database, which in turn handles the processing for all of the itemized aggregates.  This includes performing the following steps:

```
-- Update Schedule E
perform ofec_sched_e_update();
delete from ofec_sched_e_queue_new;
delete from ofec_sched_e_queue_old;
```

Which are then done again in the `update_aggregates` management command ((here)[https://github.com/18F/openFEC/blob/develop/manage.py#L180] and (here)[https://github.com/18F/openFEC/blob/develop/manage.py#L186]).  Those should probably be removed from one spot, either here or the SQL.

The schedule a and b queue cleanup steps are done in this method now on account of the partitioning support and the order in which these things need to happen, which is fine, but it looks like we forgot to account for their presence still being needed in the full rebuild step as well.

**Comment by ccostino** [comment] 2016-07-14 16:28
I think I'm also seeing to other potential problems here, but definitely want folks to verify/refute.  In the `update_aggregates` command we refresh the child tables in the partition, but in the `rebuild_aggregates` command we do not.  Shouldn't we be doing that there too, before removing any records from the queues?

Also, the `rebuild_aggregates` command runs all of the scripts in the `data/sql_incremental_updates` folder, which recreates the tables in addition to recreating the functions that are used for the nightly updates.  The schedule e updates, however, do not actually take place it looks like.  The function itself is recreated, but it is not run like it is with the nightly updates.  Shouldn't it be run, too, and then its queues cleared out as well?

**Comment by jontours** [comment] 2016-07-14 16:38
@ccostino "What I'm not sure of at the moment is if it's enough to inherit from the parent table, or if it still needs to be explicitly defined on the child table(s) as well."   It seems though, that the primary key for the child tables are being specified here right?: [https://github.com/18F/openFEC/blob/develop/webservices/partition/base.py#L117](url)

**Comment by ccostino** [comment] 2016-07-14 16:42
@jontours:  Yeah, it is, and I thought it should be, but I just wanted to double check.  A quick test would be to insert a fake record with the same `sub_id` as an existing record and see if it goes in (this could be done locally).

**Closed** 2016-08-12 17:28 UTC
Labels: Before release, Bug
