### ISSUE TITLE
Typeahead not suggesting known committees

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#2131] opened 2017-06-13 22:27 UTC
Handel's Senate committee is not among the suggested committees in the typeahead.

![image](https://user-images.githubusercontent.com/11817734/27107078-36711cb2-5064-11e7-84ac-b8e9a3e7b4ff.png)

If you submit the search, her Senate committee is amount the results.
https://www.fec.gov/data/?search=handel

Is the typeahead seen as just a suggestion and a shortcut? If you don’t see what you are looking for among the suggestions, then you submit the search receiving a full set of results?

Are people taking the suggestions of the typeahead as definitive?

**Comment by jenniferthibault** [comment] 2017-06-16 14:51
Expected committee to be returned is [Handel for Senate, Inc](https://www.fec.gov/data/committee/C00545657/)

This looks like it was supposed to be resolved by https://github.com/18F/fec-style/pull/724 -- but the problem is still happening.

**Comment by noahmanger** [comment] 2017-06-16 16:28
Looking into this today. Such a weird bug. I can see the [results are returned by the API](https://api-stage.open.fec.gov/v1/names/committees/?q=handel&api_key=DEMO_KEY), and the typeahead is set to show the top 5 results for both candidates and committees. 

Upping the limit from 5 to 10 shows the correct committees:
![image](https://user-images.githubusercontent.com/1696495/27235524-fa45e074-5275-11e7-9ce8-95f9519f5b63.png)

But it also means that for more common terms (like "Ryan for") the list will be very long:
![image](https://user-images.githubusercontent.com/1696495/27235556-0d54b514-5276-11e7-958f-ce0be1976112.png)

**Comment by jenniferthibault** [comment] 2017-06-16 16:53
Weird, so while it's SET to show the top 5 results for both, it's not. In Handel's case, it's only showing 1 committee.

Seems like there's a perception issue here too... users (press/public records office staff included) are perceiving this as a search that returns ALL matches, not only some of them. So there's some interface/copy design that could be needed.

**Comment by noahmanger** [comment] 2017-06-16 16:54
Yeah I was thinking that too. There will always need to be some limit imposed, so might be good to tweak the microcopy. But regardless, if usually you see 5 matches but in some cases you see only 1, it's logical to think that the others don't exist.

**Closed** 2017-06-20 19:47 UTC
Labels: Bug

**Comment by jenniferthibault** [comment] 2017-06-20 21:22
@noahmanger is it worth keeping this issue open or filing a new one for the content/interaction design components?

**Comment by noahmanger** [comment] 2017-06-20 21:25
Let's make a new one since this was focused on the bug.
