### ISSUE TITLE
Next election

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#1753] opened 2016-12-20 23:58 UTC
Update the API to use the table of election dates rather than a flat file.

---
## Background:
**Related** to https://github.com/18F/FEC/issues/542
https://beta.fec.gov/data/elections/?zip=68901

President: November 3, 2020

House: November 6, 2018

Senate Class 1: November 6, 2018
Arizona
California
Connecticut
Delaware
Florida
Hawaii
Indiana
Maine
Maryland
Massachusetts
Michigan
Minnesota
Mississippi
Missouri
Montana
Nebraska
Nevada
New Jersey
New Mexico
New York
North Dakota
Ohio
Pennsylvania
Rhode Island
Tennessee
Texas
Utah
Vermont
Virginia
Washington
West Virginia
Wisconsin
Wyoming

Senate Class III - November 3, 2020
Alabama
Alaska
Arkansas
Colorado
Delaware
Georgia
Idaho
Illinois
Iowa
Kansas
Kentucky
Louisiana
Maine
Massachusetts
Michigan
Minnesota
Mississippi
Montana
Nebraska
New Hampshire
New Jersey
New Mexico
North Carolina
Oklahoma
Oregon
Rhode Island
South Carolina
South Dakota
Tennessee
Texas
Virginia
West Virginia
Wyoming

Senate Class II - November 8, 2022
Alabama
Alaska
Arizona
Arkansas
California
Colorado
Connecticut
Florida
Georgia
Hawaii
Idaho
Illinois
Indiana
Iowa
Kansas
Kentucky
Louisiana
Maryland
Missouri
Nevada
New Hampshire
New York
North Carolina
North Dakota
Ohio
Oklahoma
Oregon
Pennsylvania
South Carolina
South Dakota
Utah
Vermont
Washington
Wisconsin

@jenniferthibault @emileighoutlaw @LindsayYoung @jwchumley @AmyKort @ChristianHilland

**Comment by noahmanger** [comment] 2016-12-27 22:31
@PaulClark2 the dates that we show on that page are pulled from the data that we get from you. Is there anything we should do before you update the data? We could always change the label from "Next election" to something more generic?

**Comment by PaulClark2** [comment] 2016-12-27 23:51
Do you happen yo know the name of the table or tables for these data? @ccostino @jontours @LindsayYoung

**Comment by noahmanger** [comment] 2017-01-30 23:51
While checking in on this, it looks like all the elections are now listing November 2018, but this is a problem for president:
![image](https://cloud.githubusercontent.com/assets/1696495/22446883/fa9c072a-e703-11e6-9eda-81be1e653281.png)

**Comment by PaulClark2** [comment] 2017-01-31 00:16
It's not in the data. `select RACE_PK, OFFICE, STATE, ELECTION_YR, ELECTION_TYPE_ID , CYCLE_START_DT, CYCLE_END_DT, ELECTION_DT from DISCLOSURE.DIM_RACE_INF where office='P' order by election_yr;`


RACE_PK	|	OFFICE	|	STATE	|	ELECTION_YR	|	ELECTION_TYPE_ID	|	CYCLE_START_DT	|	CYCLE_END_DT	|	ELECTION_DT
----	|	----	|	----	|	----	|	----	|	----	|	----	|	----
197210441	|	P	|	US	|	1972	|	G	|	1/1/1969	|	12/31/1972	|	11/7/1972
197611388	|	P	|	US	|	1976	|	G	|	1/1/1973	|	12/31/1976	|	11/2/1976
198012334	|	P	|	US	|	1980	|	G	|	1/1/1977	|	12/31/1980	|	11/4/1980
198413281	|	P	|	US	|	1984	|	G	|	1/1/1981	|	12/31/1984	|	11/6/1984
198814228	|	P	|	US	|	1988	|	G	|	1/1/1985	|	12/31/1988	|	11/8/1988
199215174	|	P	|	US	|	1992	|	G	|	1/1/1989	|	12/31/1992	|	11/3/1992
199616121	|	P	|	US	|	1996	|	G	|	1/1/1993	|	12/31/1996	|	11/5/1996
200017071	|	P	|	US	|	2000	|	G	|	1/1/1997	|	12/31/2000	|	11/7/2000
200418031	|	P	|	US	|	2004	|	G	|	11/8/2000	|	11/2/2004	|	11/2/2004
200818981	|	P	|	US	|	2008	|	G	|	11/3/2004	|	11/4/2008	|	11/4/2008
201219489	|	P	|	US	|	2012	|	G	|	11/5/2008	|	11/6/2012	|	11/6/2012
201619557	|	P	|	US	|	2016	|	G	|	11/7/2012	|	11/8/2016	|	11/8/2016
202015115	|	P	|	US	|	2020	|	G	|	11/9/2016	|	11/3/2020	|	11/3/2020


Can @ccostino @jontours or @LindsayYoung confirm we are using `disclosure.dim_race_inf` as the source table for these election dates?

**Comment by LindsayYoung** [comment] 2017-01-31 22:19
These election dates are coming from a flat file that is added to the database with a load_election_dates management command. This creates election dates only for the election views, we want to transfer the datasource to the dynamic data that we now have.

**Comment by noahmanger** [comment] 2017-02-01 00:13
So what's the next step on this? Do we want to have the task this sprint be to change the data source? Or should we opt for a simpler update to the flat file while we're pressed for time?

**Comment by jontours** [comment] 2017-03-02 15:05
This may be a bit more work than originally thought.  After talking with @LindsayYoung last night it may be best to completely rework the logic behind the endpoint `elections/search`.  The logic in there is rather convoluted, and doesn't even reference the table `disclosure.dim_race_inf`.  Also, the data for the current endpoint uses the ElectionResults (not the flat file as originally thought) model to generate the dates we are seeing, and is attempting to derive election date, which as we see it does only partly successful.

**Comment by jontours** [comment] 2017-03-02 15:06
Oh and @noahmanger, I can probably research this as well, but do we know what front-end resources use `elections\search` besides this one?  Want to ensure their are no regression issues.

**Comment by PaulClark2** [comment] 2017-03-02 16:03
`disclosure.dim_race_inf` only includes general and special general elections. I'm not sure if `ElectionResults` includes primaries, run offs and generals.

**Comment by noahmanger** [comment] 2017-03-03 00:59
I just made a clean issue for this https://github.com/18F/openFEC/issues/2225

So I'm closing this one.

**Closed by noahmanger** 2017-03-03 00:59 UTC
Labels: Bug, Needs grooming
