### ISSUE TITLE
Design solution for displaying reclassified statutes

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1736] opened 2016-12-15 01:32 UTC
So that users understand the results they get when searching by a previous statute citation, display some signifier that conveys that results matching the current citation are shown.

---

This is a small design issue for finding a way to convey that the old code and new code are mapped to each other when searching through legal resources. Users may be confused if they search for one classification and get results matching a completely different classification, even though it's the same code. 

When designing, we should consider:
- [ ] How this is explained in search fields

The question of how this shows up in the results will be addressed in the design of the results display, which is occurring in a different issue.

**Comment by nickykrause** [comment] 2016-12-23 16:32
Just jotting down some thoughts so that I don't lose them:

As we implement more filters and search capabilities for legal resources, there are implications for the results display that pose interesting challenges, which we did not see on the data side when we were presenting results in table form. For example, over in issue #1735, one of the things we're discussing is how the addition of the `document type` filter will require us to display the links to the documents themselves, as well as where the search terms appear for each document type.

Similarly, as we talk about adding `search by citation` functionality to the MURs (and possibly other legal resources), we need to make sure that users can make a clear connection between their search terms (a citation) and the results they get, but figuring out how to do this won't be as straightforward as adding a column to a data table. 

For reference, let's take the currently-proposed design from #1735, for MURs:

![ae509dee-c233-11e6-98ba-c6d1175813f5](https://cloud.githubusercontent.com/assets/1450173/21458094/76d9b8d8-c8f9-11e6-8877-6591d165a542.png)


- If, as we have talked about in issue #1735, we implement citation searching by crawling the text of the case documents, then we could make a visible connection between the search terms and the results simply through keyword highlighting. However, as we've noted in issue #1735, there will be some problems with searching the text for citations (e.g., potentially bad OCR-ing, or non-citation matches, such as statute 30101 yielding matches for a ZIP in GA). 
    - Of course, the keyword highlighting solution for the results display might make it tricky for us to display the "reclassification translation," which this issue is meant to address. 

- If we implement citation searching by meta data (which has its own limitations -- see issue #1735), then we have different implications for the results display, assuming that the display leans heavily on the `document type` breakdown, as proposed above. As far as I can tell, the citations meta data for MURs are not entered by document, but rather by the whole case. So, we'd probably need to display citations in the results at the "case level" -- the gray bar containing info about the case as a whole -- rather than at the "document level".

- Another thing to consider is that there are additional advanced search features and filters on the horizon for MURs (and other legal docs), so the results display will continue to be strained in new ways. For example, how will the above design be affected when the `Final commission disposition` filter is added, or the `Respondent` filter? Because this is case-level information, it seems likely that it will be grouped with other case-level things, and not impact the doc-level display. But, that said, we are reaching a point where there will be a _lot_ of information present in the results display, since we need to make connections between the results display and many different types of filters, but without the benefits of a tabular display, like we have on the data side.

^ The above discussion leads me to two thoughts: 

(1) We need to know how we want to search citations, in order to complete the task outlined in this issue. It seems most likely that we will search the text of the documents, despite the possible problems.

(2) It might be helpful to reflect holistically on how we could best approach the results display for the legal resources, given the number of additional filters we'll be adding. We don't have to design the whole thing at once, but, maybe it is worth considering how information-loaded we are willing to let the interface become. Thinking more holistically may also prevent us from designing separate solutions that might not work together (i.e., I designed the `doc type` results display over in #1735), but I'd already be making updates to that proposed-but-not-yet-approved design over here, in this issue, in order to accommodate citation display + reclassification.

**Comment by nickykrause** [comment] 2016-12-27 17:48
After speaking with Noah and Jen about the above comment, we have agreed to approach the design of the MUR search results display holistically, which means that we'll consider the implications of adding all the filters we know we wish to add, rather than adjusting the results display one filter at a time.

Issue https://github.com/18F/openFEC-web-app/issues/1761 has been created to address the work of documenting the filters associated with each resource, as well as the user needs that will influence the design of the results display. So, the design of the results display is moving to that issue, and this issue will focus exclusively on the question of the search fields themselves. I have adjusted the completion criteria to reflect this.

**Regarding the citations, there are two outstanding issues:**
- How will we search the citations?
    - Our current thinking trends toward searching the text of the documents, rather than the meta data. See discussion above.
- How will the search fields work (including the question of how the reclassification will be handled)? 
    - For this, I maintain my suggestion that we use a typeahead within the dedicated "citations" search fields to display a "translation" between the two classifications. For example:

<img width="273" alt="screen shot 2016-12-27 at 11 07 32 am" src="https://cloud.githubusercontent.com/assets/1450173/21504449/b2c773c0-cc24-11e6-9f39-fba4a8086bba.png">

The idea here is that the user could start typing `301`, for example, and the system would suggest the associated Title 52 citations that start with those numbers, as well as displaying what those citations used to be. If there were also a Title 2 citation that started with `301`, then I think it would make sense to include that in the typeahead, like:

<img width="270" alt="screen shot 2016-12-27 at 11 14 31 am" src="https://cloud.githubusercontent.com/assets/1450173/21504570/a8a77268-cc25-11e6-9ae2-4cc5f5612899.png">

Some things about the typeahead logic:

- I don't know if the latter case would ever occur (i.e., where there is a Title 52 and a Title 2 citation that begin in the same way, as with `301...`). But, if it did, I am not sure how the Title 2 matches and the Title 52 matches would be prioritized against each other, since we can only display so many matches. It would be helpful to understand if this case is possible. What is the best way to determine this? 

- I am not sure how many results it is reasonable to display in the typeahead. There could be many Title 52 citations that start with `301...`. Again, it would be helpful to better understand the universe of possible citations we are working with.

- The typeahead would only appear on the dedicated `citations` search fields. If the user enters a citation into the regular keyword search (which would also search the text of the documents for that string), then the typeahead would not appear (nor would the "reclassification translation").

- My current thinking is that the typeahead would help to ensure that users enter the citations correctly and hopefully will yield the best results. So, the design currently assumes that we would force the user to select a suggestion from the typeahead (rather than allowing them to search their own string). However....
    - As mentioned previously, I am not sure what the "correct" citation format would be for us to use in the typeahead, because I don't know if the citations appear in some uniform way in the docs, and, further, whether or not the OCRing process was good enough to reliably pull them out in a usable way.

- Again, as mentioned previously, some of the search results for a citation (e.g., `30101`) might yield non-citation results (e.g., when `30101` appears as a ZIP code in a doc). This could be confusing for users who have chosen to the use the `citation` search fields in the hope that only citation matches will be returned, but it seems unavoidable unless we search the meta data instead of the text of the docs.

Some things about this interface:
- I am not sure if it is necessary to display the "52" and the "2" before each citation in the typeahead. It may reduce clarity and readability. However, it also adds clarity the the idea that some of the suggested citations are formatted according to Title 52 versus Title 2. 
    - If we keep the 52s and the 2s, it might be helpful if the typeahead could highlight the part of the citation where the match is occurring:
<img width="278" alt="screen shot 2016-12-27 at 11 27 52 am" src="https://cloud.githubusercontent.com/assets/1450173/21504801/8c6b009a-cc27-11e6-81c4-b986f8523dfe.png">

Assuming that we like the idea of a typeahead as a possible solution for "translating" reclassifications to users, then, in order to proceed with figuring out (a) exactly how the typeahead might work, and (b) what its limitations might be, I will probably need input from a developer -- presumably @vrajmohan? (cc @noahmanger). 

Or, if we have general concerns about the typeahead and want to explore a different design solution, I can do that.

**Comment by noahmanger** [comment] 2016-12-27 22:40
**Typeahead logic:** For the finer points here (how many results, how to handle it if similar numbers show up in multiple places), I think we'll just need to start playing with it with the actual data loaded up. I'm not sure we'll be able to tell what makes the most sense yet. 

**On the format of the citation:** As we discussed in grooming, we're going to normalize the formatting of all of the citations, which will be stored in metadata, so that selecting a typeahead suggestion will match exactly. 

**Match highlighting:** Yep, this is totally possible. I think it's helpful to have the 52/2 there.

I don't think there's anything else we need to figure out here, do you?

**Comment by nickykrause** [comment] 2016-12-27 22:46
@noahmanger: No, I don't think there is anything else to design

The only thing I'm not sure of is whether or not the regulatory citations are also affected by the reclassification. I don't think they are, but I'm not sure. Do you know? If not, I will ask Jennie.

**Comment by jenniferthibault** [comment] 2016-12-28 16:46
@nickykrause I really dig the reclassification hint in the typeahead! I'm not sure this is the only place we'll need to offer assistance to users, but it's a big one for sure. 

One thing I'm noticing is that it's hard for me to "read" the numbers in the citations without their typical U.S.C./CFR and § breaks. What if we included those formatting pieces in the typeahead matches? This observation speaks to your question about clarity, I believe.

Using your last screenshot, if someone were typing `301` in the Statutory citation search box, the matches presented would say
`52 U.S.C. §30101 (formerly 2 U.S.C. §431)

What do you think?

**Comment by jenniferthibault** [comment] 2016-12-28 16:48
Oops, I had this issue open in a tab and so it hadn't refreshed before I posted and didn't see the comments from Noah yesterday. My question may be covered under "Normalizing the citations"?

**Comment by nickykrause** [comment] 2016-12-28 16:49
@jenniferthibault That makes sense to me! 

And I don't think we had explicitly stated what "normalizing the citations" would mean, beyond making them all the same format. So, it is good to be clear that we would normalize them and then display them in the manner that you indicated.

**Comment by noahmanger** [comment] 2016-12-28 17:54
I just realized there's an element of this that we haven't addressed, which is how re-classified statutes should show up in the citation box on an individual page. Picture a couple scenarios:

**Scenario 1**
- User searches for `52 U.S.C. §30123` in AOs
- The results include newer AOs that cite `52 U.S.C. §30123` as well as older ones that cite `2 U.S.C. §30123`
- If you go to an older AO with the old citation, what does the sidebar show? Does it only include `2 USC`, only `52 USC` or both (like the typeahead)?

**Scenario 2**
- Conversely, a user could search `2 U.S.C. §30123`
- They get both `52` and `2` results
- When they go to a newer one that includes `52 USC` citations, should that also mention "formerly 2 USC" in the sidebar?

Re-opening.

**Comment by noahmanger** [comment] 2016-12-29 00:52
As far as how we note the reclassified code, I think what you're suggesting makes sense. I _think_ we always want to link to the 52 U.S.C, but I'm not so sure. 

But yeah, I think we might want to rethink this pattern.

**Comment by jenniferthibault** [comment] 2016-12-29 00:59
A few notes on the layout that may solve some of the problems!

- The [OG intended designs from Ed Mullen](https://gsa.invisionapp.com/share/AR7U3Y662#/167711253_AO_Index) do have longer content in the summary section that would be pulled from the FEC Record. Digging deeper, I learned a while ago that the preference is to actually pull this summary data from the Weekly Digests (Just like the MUR disposition info)
- 
<img width="1090" alt="screen shot 2016-12-28 at 7 42 08 pm" src="https://cloud.githubusercontent.com/assets/11636908/21534518/673ae6cc-cd36-11e6-8643-55f0ef709af2.png">

### But!
- The most updated patterns dictate that when the citations sidebar is implemented, the main content container and the citations container are their own vertical columns. So the sidebar would not need to dictate the length of the summary container:

- ![screen shot 2016-12-28 at 7 46 42 pm](https://cloud.githubusercontent.com/assets/11636908/21534534/a67674a0-cd36-11e6-8b28-f4b2df614313.png)

### However! 
- Since these were made, there's been an evolution of the Resources panel to better accommodate long lists of citations. If we wanted to introduce the side-nav to this page, like we have on [canonical MUR pages](https://beta.fec.gov/data/legal/matter-under-review/4905/), 
 we could add "Legal citations" to the side nav and use the horizontal version of the pattern, which is established in the [AO process page](https://beta.fec.gov/legal/advisory-opinions/process/):

<img width="1039" alt="screen shot 2016-12-28 at 7 54 11 pm" src="https://cloud.githubusercontent.com/assets/11636908/21534606/9c4c10f6-cd37-11e6-8baa-6716fcdf3d5c.png">

<img width="1023" alt="screen shot 2016-12-28 at 7 56 07 pm" src="https://cloud.githubusercontent.com/assets/11636908/21534619/b5ff897e-cd37-11e6-8ce0-16636c245ec7.png">

That would make it so that the canonical AO page and the canonical MUR page are using more similar templates overall.

**Comment by nickykrause** [comment] 2016-12-29 04:06
@jenniferthibault Thank you for the history! This is so helpful! 

@noahmanger (and Jen): Do we have an issue out there to pursue the idea of using FEC Record summaries as the summaries for AOs (per Ed's original design)? It seems worth doing. Plus, it seems related to our known issue of using a plain language source (i.e., the Weekly Digests) for the `Disposition` section of the MUR `Summary`. 

I agree that the side nav + horizontal citations pattern would work best here, especially if there is a risk that the citations will be quite lengthy. (Since we are also eventually going to add "AOs that cite back to this AO," the list of citations will continue to grow the older an AO gets, and the more it is likely that things link back to it.) Plus, this page will eventually become longer (once `Entities` are added), so the side nav will be helpful.

**Comment by jenniferthibault** [comment] 2016-12-29 15:56
I'd love to take a quick pass on the fine details of visual styling here when it's ready, but on the whole 👍 👍 

I think the Citations sections could use a real close look at all the point for consistency: to start with, 
- What is it called? On the AO Process page, we call it "Legal citations"
- How do we format AO links? Do they have titles, or just AO numbers? (Fwiw, I think it would be helpful to have "AO" in front of the YYYY-## format, because digits alone are kind of austere.
- How should we plan for distinguishing citations referenced in this AO and future AOs that reference this one?

Here's another version of that panel with a few variations, just to show all the things we should make decisions on. (note: this is getting far away from the original point of this issue....maybe we should break out one for AO page styling if we are committing to reconfiguring the page template, and one for citations copy formatting review?)

![screen shot 2016-12-29 at 10 54 37 am](https://cloud.githubusercontent.com/assets/11636908/21547611/34f72476-cdb5-11e6-866e-d5782197fdc7.png)

**Comment by nickykrause** [comment] 2016-12-29 16:18
I agree that they should be separate issues. The original point of this issue was only to address how the citation classification translation would appear at the time of search (thus, I addressed how it would work in the typeahead).

This issue was then re-opened to deal with how the citations would appear on the canonical page, but it does not address, as you have noted:

- What this will look like once we design how to handle bi-directional citation linking
- How the AO citations should be formatted (for consistency)
- Exactly what the citations section on pages are called (`Legal Citations` vs. `Cited in this Opinion`, etc.)
    - FWIW, I am aware that there is inconsistency, but I think that the `Cited in this Opinion` heading makes it clearer that, at least in the case of AO citations, we are talking solely about the citations that appear in the AO Final Opinion, rather than throughout all the documents. 

The other things that this issue surfaces but does not address are:
- How do we get the more robust and plain language AO summaries from the FEC Record, as Ed designed?
- How will the citations translations appear in the search results display for the various legal resources?
- How can we link to sub-sections of a citation, when we know this is a user need/want?
- What citations needs do we have for the other legal resources canonical pages (ADRs, MURs, AFs)? 

There are lots of questions. I think I was trying to keep the scope of this issue small so that it could be managed in this sprint. 

I can create more issues for these other points (for the ones that don't exist yet)...

**Comment by emileighoutlaw** [comment] 2016-12-29 16:30
I'm just popping in to surface how we've formatted AO links in our content sections and to give high fives to Jen for putting the word "austere" in a GitHub comment. 

Generally, we've been doing:
> AO YYYY-##
> _Requestor name_

So, in situ:
![screen shot 2016-12-29 at 10 30 05 am](https://cloud.githubusercontent.com/assets/10552702/21548416/d2e0308c-cdb1-11e6-9126-c2ebdea6e30c.png)

**Comment by nickykrause** [comment] 2016-12-29 16:33
Thanks @emileighoutlaw 

and +1 for the diction points to Jen  :smile:

**Comment by jenniferthibault** [comment] 2016-12-29 16:35
It was a vocab word in 9th grade. Something involving an "austere steer" who chose to sit on a roof instead of joining the party. Those thing stick with you!

**Comment by nickykrause** [comment] 2016-12-30 18:42
Some answers to the questions we raised:
- What will the AO citations section look like once we design how to handle bi-directional citation linking?
    - As I have discovered and documented over in https://github.com/18F/fec-eregs/issues/326, it sounds like we might not actually _have_ the information needed to display the Statutes/Regs and Advisory Opinions that are "Cited in this AO." 
    - In an email exchange with Jennie and Cheryl, they revealed that the only way to figure out which citations appear in an AO is through a hit or miss keyword search that relies on good OCR-ing. There apparently isn't meta-data about what citations appear in an AO. 
    - As for the "AOs Citing this AO," we have already talked synchronously about how that might be accomplished with some engineering magic, and the users have confirmed that it is something they want (because they already have it). The "AOs Citing this AO" seems to be the priority, because it will help us to achieve feature parity with the old system. The ability to also see what citations appear within a given AO would be a bonus, but we'd need to figure out how to get that information.
- How the AO citations should be formatted (for consistency)
   - This point can be discussed in https://github.com/18F/fec-eregs/issues/326 or turned into its own content-y issue.
- Exactly what the citations section on pages are called (`Legal Citations` vs. `Cited in this Opinion`, etc.)
   - This point can be discussed in https://github.com/18F/fec-eregs/issues/326 or turned into its own content-y issue.


- How do we get the more robust and plain language AO summaries from the FEC Record, as Ed designed?
    - This issue seems related to https://github.com/18F/fec-eregs/issues/294, where we have talked about getting better, plain-language summaries for MURs as well. It seems that for both AOs and MURs, we are interested in pulling summary information from the Weekly Digests, but we are having trouble getting approval to do that. I created this new issue to re-establish the conversation about plain-language summaries, but for both MURs and AOs: https://github.com/18F/fec-eregs/issues/327
- How will the citations translations appear in the search results display for the various legal resources?
   - This issue will be addressed as a part of the work being done on the UX/Visual design of the results display for advanced legal resource searching, which is over here: https://github.com/18F/openFEC-web-app/issues/1761 
- How can we link to sub-sections of a citation, when we know this is a user need/want?
    - I created an issue in the research/testing repo to capture this: https://github.com/18F/fec-testing/issues/23
- What citations needs do we have for the other legal resources canonical pages (ADRs, MURs, AFs)?
    - This is being covered in https://github.com/18F/fec-eregs/issues/326, where we are exploring how to consistently display various informational elements (including citations) across the different legal resource canonical pages.

Given that the outstanding questions are all being addressed elsewhere, I think we can close this issue, since its original scope dealt only with the display of reclassified statutes in the search box. The design for that is as follows:

<img width="288" alt="screen shot 2016-12-30 at 12 41 57 pm" src="https://cloud.githubusercontent.com/assets/1450173/21570631/67e26d7c-ce8d-11e6-8b00-16bb2449631e.png">

**Closed by nickykrause** 2016-12-30 18:42 UTC
Labels: Mothership, Work: Design
