### ISSUE TITLE
Disbursements Page

### ISSUE THREAD

**Issue by ChristianHilland** [18F/openFEC-web-app#1123] opened 2016-03-10 21:47 UTC
Below are comments in connection with the Disbursement page of the beta site. You may be aware of some of these issues already. Please let me know if you have any questions.

1) The Recipient Information section includes Recipient (Committee) and Recipient (Non-Committee) fields.  I think having two separate search fields may be confusing to the average user.  Does anyone have any thoughts about this or whether it makes more sense to have one search field?

2) Disbursement Purpose Category: This field on Schedule B of the FEC forms is not required to be completed by the filer and is not reviewed by RAD. I'm concerned that users will select this field on the Disbursement page and think that the results will be all-encompassing. Any thoughts about this or the possibility of removing this field from the page?

3) Amount field: Would it be possible to right justify the amounts in this field?

4) Suggestion to the left-menu: I wonder if it would be helpful to include a drop-down field for users to search across a particular committee type. For example, if a user wanted to search for all disbursements for just presidential candidate or House candidates in CA's District 4 or all PACs, they would be able to do that.

5) Addition of the Memo Code field is important as it displays transactions that should not be taken into consideration in the overall spending total.

6) Not all column headers are clickable/sortable.

7) After clearing filters after the search of a particular committee, the committee name is still displayed on the left-hand menu. Should this be the case?

8) We've received lots of great feedback on this page as this search feature is not currently available on FEC.gov.  The itemized transaction download feature is eagerly awaited by the public.

**Comment by noahmanger** [comment] 2016-03-11 02:56
Thanks! Here's my thoughts:

1. Agreed. We're actually consolidating these into a single field in the next release.
2. I think even though the disbursement purpose field isn't required it's still useful, but curious what @LindsayYoung thinks.
3. Amount field: Do you mean the column in the table or the filter? We have a separate issue for right aligning the numbers. I think it's a good idea.
4. This is an interesting idea. Let's look at it when as we're building out these datatable pages with new filters. 
5. Can you clarify this?
6. The sortability of columns is a known issue. The problem is it's very slow to sort certain fulltext columns.
7. You caught a bug! Filing a new issue for this.
8. Glad to hear! Hope to have this done ASAP.

**Comment by ChristianHilland** [comment] 2016-03-11 17:03
Thank you for your responses.  A couple of follow-ups:

3) I meant the Amount column in the table.  

5)  Some disbursements are classified as memo entries, which means that particular disbursement amounts are not included in the overall spending total.  For example, a committee is required to disclose its payment to a credit card company.  Reporting regulations require that the committee also include the original credit card charges that made up that expense (ie. Marriott for Hotel Expenses, Catering, etc.). Those charges are reported as memo entries so that the amounts aren't counted twice.

My suggestion is to display the Memo Code field within the table on the Disbursements page. Any memo entries display an X  in that field.

**Comment by noahmanger** [comment] 2016-03-11 22:55
Thanks for clarifying / explaining. We have the memo code in the details panel. Is that enough, or are you suggesting it should be a column? We're already crunched for space, which is my only concern. @PaulClark2 and @LindsayYoung what do you think?

**Comment by ChristianHilland** [comment] 2016-03-12 17:32
It's not a problem if the memo code field isn't displayed. Most users will have to export the full set of data regardless.

**Comment by noahmanger** [comment] 2016-03-19 00:09
Sounds like we've captured all of these issues in other places, so I'm closing this. Thanks!

**Closed by noahmanger** 2016-03-19 00:09 UTC
