### ISSUE TITLE
Bug: Display issues for some of place/city names

### ISSUE THREAD

**Issue by wluoFEC** [18F/openFEC-web-app#685] opened 2015-09-16 15:01 UTC
example:

![image](https://cloud.githubusercontent.com/assets/7440932/9908508/fb7560fc-5c61-11e5-9b6d-5518ad05bb97.png)

**Comment by jmcarp** [comment] 2015-11-05 20:15
I've seen this before, but now I can't reproduce the problem. I'm wondering whether Stamen improved their map tiles, or if this only happens in some browsers. @wluoFEC, would you mind checking the production site and trying to replicate this? If you continue seeing this problem, could you let me know which OS and browser you were using? Thanks!

**Comment by noahmanger** [comment] 2016-01-26 23:47
I'm not seeing this issue, so moving to icebox.

**Closed** 2017-09-28 15:46 UTC
