### ISSUE TITLE
Preview Pane not displaying correctly for single candidate

### ISSUE THREAD

**Issue by onezerojeremy** [18F/openFEC-web-app#518] opened 2015-08-25 17:02 UTC
URL: https://fec-dev-web.18f.gov/candidates?name=huffman&cycle=2016&cycle=2014&cycle=2012

Upon name searching and finding one candidate on the candidate browse page, clicking on the candidates row triggers a preview pane that does not appear correctly. 

![preview pane display bug](https://cloud.githubusercontent.com/assets/474916/9473534/4d43a2bc-4b29-11e5-8b82-cf249f1e6a9a.gif)

**Comment by noahmanger** [comment] 2015-08-26 01:42
Ah yep. Known bug. I'm on it!

**Comment by jmcarp** [comment] 2015-08-27 16:24
Duplicate of #428.

**Closed** 2015-08-28 15:51 UTC
Labels: bug
