### ISSUE TITLE
IE data oddity

### ISSUE THREAD

**Issue by PaulClark2** [18F/openFEC-web-app#2034] opened 2017-05-12 14:38 UTC
From Slack: 

Paul Clark [3:18 PM] 
I'm looking at IEs made by C00490375, https://beta.fec.gov/data/committee/C00490375/?tab=independent-expenditures-committee. The page includes this note, `These totals are drawn from quarterly, monthly and semi-annual reports. 24- and 48-Hour Reports of independent expenditures aren't included.` (edited)

[3:19] 
When I click on the amount ($35,000), I'm taken to this page, https://beta.fec.gov/data/independent-expenditures/?data_type=processed&committee_id=C00490375&is_notice=false&candidate_id=H8CA34134&support_oppose_indicator=S&min_date=01%2F01%2F2017&max_date=12%2F31%2F2018, with no results. (edited)

Lindsay Young [3:22 PM] 
well, that makes no sense

Paul Clark [3:22 PM] 
When I click on the 24- and 48-hour reports button, the app displays the $35,000 IE.

[3:22] 
That's what I thought :_)

[3:23] 
The committee did file a 24- and 48-hour report disclosing $35,000 in IEs.

[3:23] 
The committee also filed a special post-general disclosing the IE (edited)

Lindsay Young [3:25 PM] 
maybe it is out of sync? I re-ran schemas, in the middle of the day that updates most but not all of the data

**Comment by LindsayYoung** [comment] 2017-05-16 19:28
It would be good to check do see if the record is in `fec_vsum_f57_vw` and if not see of there is something like a join that is filtering it out.

Here is where we create schedule e
https://github.com/18F/openFEC/blob/develop/data/sql_setup/prepare_schedule_e.sql

@PaulClark2 do you have a id for the missing record handy?

**Comment by jwchumley** [comment] 2017-05-17 11:49
The transaction that should be showing up from the Post Special General report is sub_id=4050420171400822071

**Comment by jwchumley** [comment] 2017-05-17 12:32
The sub_id is 4050420171400822071 but It isn't in the fec_vsum_f57_view and it should'nt be. It came in on a form 3x and is in the sched_e table not the f57 table. I looked at the code here: https://github.com/18F/openFEC/blob/develop/data/sql_setup/prepare_schedule_e.sql

and if you run the very first part of the code it does pick up the row with sub_id 4050420171400822071:
2 drop table if exists ofec_sched_e_tmp; 
3 create table ofec_sched_e_tmp as 
4 select 
5     *, 
6     cast(null as timestamp) as timestamp, 
7     image_pdf_url(image_num) as pdf_url, 
8     coalesce(rpt_tp, '') in ('24', '48') as is_notice, 
9     to_tsvector(pye_nm) as payee_name_text, 
10     now() as pg_date 
11 from fec_vsum_sched_e_vw; 

this is followed by a few more inserts from other  views which should not effect the row and then by triggers that include deletes.

If try selecting from ofec_sched_e_tmp  the 4050420171400822071 row doesn't exist so I think one of these deletes is removing it but I don't know which one. I don't see anything else that might cause it.

create or replace function ofec_sched_e_update_queues() returns trigger as $$ 
133 declare 
134     start_year int = TG_ARGV[0]::int; 
135 begin 
136     if tg_op = 'INSERT' then 
137         delete from ofec_sched_e_queue_new where sub_id = new.sub_id; 
138         insert into ofec_sched_e_queue_new values (new.*); 
139         return new; 
140     elsif tg_op = 'UPDATE' then 
141         delete from ofec_sched_e_queue_new where sub_id = new.sub_id; 
142         delete from ofec_sched_e_queue_old where sub_id = old.sub_id; 
143         insert into ofec_sched_e_queue_new values (new.*); 
144         insert into ofec_sched_e_queue_old values (old.*); 
145         return new; 
146     elsif tg_op = 'DELETE' then 
147         delete from ofec_sched_e_queue_old where sub_id = old.sub_id; 
148         insert into ofec_sched_e_queue_old values (old.*); 
149         return old; 
150     end if; 
151 end

**Comment by jwchumley** [comment] 2017-05-17 17:45
Helen found that the missing sched E  is in dev:  fec-govcloud-dev.cfojp1ao5rbz.us-gov-west-1.rds.amazonaws.com

but it isn't in the production tables:  fec-govcloud-prod.cfojp1ao5rbz.us-gov-west-1.rds.amazonaws.com

@lindsay

**Comment by jwchumley** [comment] 2017-05-17 17:45
@LindsayYoung

**Comment by ccostino** [comment] 2017-05-19 15:51
@PaulClark2, @jwchumley, @LindsayYoung, and @noahmanger - if this data is in dev but not production and based on what I'm seeing above, it looks like we just need to rebuild schedule E or at least run updates on it manually?

**Comment by noahmanger** [comment] 2017-05-19 17:53
@LindsayYoung  just told me that the schedule E table was rebuilt with the last partitioning, and I see that the problem is now resolved. Closing.

**Closed by noahmanger** 2017-05-19 17:53 UTC
Labels: Bug, Needs grooming, Pre-flip
