### ISSUE TITLE
Design interface for searching through MUR document types

### ISSUE THREAD

**Issue by noahmanger** [18F/openFEC-web-app#1718] opened 2016-11-30 22:24 UTC
So that legal researchers can find the most relevant results for their research, make it possible to perform a search within only certain document types in MUR cases.

---

This is a known, really important capability to provide people searching through MURs (and eventually, ADRs). This task is to design two elements of a revised MUR search interface that are required for people to be able to limit their search to different document types.

First, we need to determine how users specify a document type. The pattern we designed for this same thing with AOs is checkboxes with a "more" dropdown:

![image](https://cloud.githubusercontent.com/assets/1696495/20773596/66487918-b707-11e6-86af-c16d703f9636.png)

The question, though, is what are the options, which live in the dropdown, and which is prioritized first, and what's default?

Second, we need to determine how we display results. An AO search result specifies the different documents that hits show up in:
![image](https://cloud.githubusercontent.com/assets/1696495/20773620/8a76bc14-b707-11e6-8647-513bd33e5bd9.png)

I think we should use this as a starting point as it's an established pattern. But we need to verify that this would make sense for MURs.

@amypike @amykort @jwchumley (and Jennie, via Jeff): do you have initial thoughts on these two questions? If we can't resolve these here, we can always discuss over video or include in our conversations with power users next week.

**Completion criteria:**
- [x] Determine the order and position of document type options for MURs
- [x] Determine what (if any) are enabled / disabled by default
- [ ] Determine how we're displaying results

**Comment by nickykrause** [comment] 2016-12-09 21:10
Quick update here: 

I'm in the middle of a string of interviews with enforcement users, and it is already becoming clear that the document types we should pull out of the "more" drop-down, at least for a first iteration of the filters, would be `General Counsel's Reports` and `Conciliation Agreements`

As for whether or not these should be searched by default, that remains to be seen.

**Comment by vrajmohan** [comment] 2016-12-13 20:31
You are reading it correct. I noticed the following document types for MURs:
 Certifications
 Civil Penalties, Disgorgements and other Payments
 Civil Penalties, Disgorgements and Other Payments
 Civil Penalties, Disgorgements, Other Payments and Letter of Compliance
 Complaint, Responses, Designation of Counsel and Extensions of Time
 Complaint, Responses, Designation of Counsel andExtensions of Time
 Conciliation Agreements
 General Counsel Reports, Briefs, Notification and Responses
 General Counsel Reports, Briefs, Notifications and Responses
 Statements of Reasons

Being a free-form text field, there are minor variations in spelling - something we should watch out for if we are trying to match _exact_ values.

**Comment by nickykrause** [comment] 2016-12-13 23:18
Thanks, @vrajmohan.

I was originally thinking about this `document type` filter for MURs as being a checkbox filter, which would be applied in the same way that we are applying document types to AOs. So, like this:

<img width="286" alt="screen shot 2016-12-13 at 5 03 08 pm" src="https://cloud.githubusercontent.com/assets/1450173/21163014/14f15ac2-c156-11e6-9c84-0ef2479a6e35.png">


But, it seems like there are complications to implementing something like that, using the doc type classifications we have for MURs (carried over from EQS). Those complications include:
- The filter labels would be really long -- e.g., `General Counsel Reports, Briefs, Notifications, and Responses`, as mentioned above
- The doc types are not as granular as we want...e.g., `General Counsel Reports` (GCRs) are lumped in with a bunch of other doc types, and `Factual & Legal Analyses` (F&LAs) are not even distinguished as a document -- they are lumped in with other kinds of "Notifications"
- As you explained in your comment, the doc type classifications are inconsistent (variations in spelling/punctuation)

--- 

To determine where we go from here, I am trying to understand what options we have. It seems like we can:

- Discuss having the FEC reclassify these documents
- Find some other technical solution...? Meaning: some solution for identifying doc types as being GCRs or F&LAs, which are the two key doc types that we can't currently separate out.

Perhaps the latter is impossible. I am not sure. I was looking in EQS, and I see that the filename is the only obvious way to tell them apart:

<img width="739" alt="screen shot 2016-12-13 at 5 07 26 pm" src="https://cloud.githubusercontent.com/assets/1450173/21163204/47dd1a56-c157-11e6-946d-993e7f584e28.png">

---

The user interviews suggest that being able to filter by GCRs and F&LAs is ideal -- and, further, that searching those specific doc types (plus two others) by default would be helpful in understanding which MURs are relevant to them.

I am trying to determine what it would take for us to be able to do that, even if it means understanding that the FEC would need to do something on their end.  

Maybe it would make sense to chat synchronously? @noahmanger do you have any thoughts?

**Comment by noahmanger** [comment] 2016-12-14 02:47
Let's check with @jwchumley and Jennie if the data is actually available to separate out GCRs and F&LAs. If it's not, it might be worth looking into if deriving the categories from the document title is possible, but this seems prone to even messier data. 

If we need to move forward with them as a single thing, we may just have to do that. @vrajmohan is that an exhaustive list of the document types that show up in the data? If so, seems like we could probably normalize the data, no?

As for for the format of the filter, I think we need to stick with the checkbox, even though it'll be a long label.

**Comment by vrajmohan** [comment] 2016-12-14 09:45
Yes, that's an exhaustive list, and, yes, we can normalize the data.
However, unless we do something to fix the root cause at the source, more variations could creep in as time goes by.

**Comment by nickykrause** [comment] 2016-12-14 14:38
Thanks, Noah and Vraj! 

I agree, Noah, that we don't want to introduce messier data, and that there may be nothing we can do. 

I would also love to hear what the FEC folks think!

**Comment by noahmanger** [comment] 2016-12-14 19:59
Circling back with info from Slack: the only way to distinguish between GCRs and F&LAs is the document description, which is a free text field that's populated by hand, which means its inconsistent.

**Comment by nickykrause** [comment] 2016-12-14 20:01
Thanks, @noahmanger - So, do you think we should we move forward with designs assuming that we won't be able to make the distinction?

**Comment by noahmanger** [comment] 2016-12-14 20:13
That's what I think, yeah.

**Comment by jwchumley** [comment] 2016-12-14 20:15
I agree.

________________________________

**Comment by nickykrause** [comment] 2016-12-16 01:28
Two of this issue's three completion criteria are complete, and we will be moving the third one to https://github.com/18F/openFEC-web-app/issues/1735.

**Here were the three criteria:**
1. Determine the order and position of document type options for MURs
2. Determine what (if any) are enabled / disabled by default
3. Determine how we're displaying results

Items 1 and 2 are addressed in the following screenshot:
<img width="230" alt="screen shot 2016-12-15 at 6 16 49 pm" src="https://cloud.githubusercontent.com/assets/1450173/21248243/53a426e0-c2fb-11e6-81f1-7e834114181e.png">

As this shows, we are recommending that `General Counsel's Reports, Briefs, Notifications, and Responses` as well as `Conciliation Agreements` are not only visible outside of the "More" menu, but also that they are searched by default. 
- The reason for this is that our user research (https://github.com/18F/fec-testing/issues/16) revealed that these document types are given the most "weight" by users as they conduct searches. If the user's search criteria appears in these document types, then it is likely that the MUR in question is relevant for them. (Note: Ideally, the `General Counsel's Reports` and the `Notifications with Factual & Legal Analyses` would be broken out as individual filters, but, as the above discussion explains, this is not possible). 

- The `Statement of Reasons` should also be pulled out of the "More" menu, but _not_ searched by default. The rationale for this is that (a) fewer of the users mentioned this document type as being essential to determining relevance, and (b) having this document type visible but _not_ checked can visually communicate to users that there are more document types that could be selected, although they are not searched by default (i.e., reinforcing the "More" menu functionality).

**The final completion criteria was: Determine how we're displaying results**

A first draft of a possible results interface is available here: https://github.com/18F/openFEC-web-app/issues/1735.

We are moving the discussion to that issue because it deals with additional filters beyond document type, all of which will have some impact on the results display.

Closing this issue.

**Closed by nickykrause** 2016-12-16 01:28 UTC
Labels: Mothership, Work: Design
